apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust-backend
  namespace: wanderlust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sujalll11/wanderlust-backend-beta:v2.1
        ports:
        - containerPort: 8080
