apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust-frontend
  namespace: wanderlust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sujalll11/wanderlust-frontend-beta:v2.2
        ports:
        - containerPort: 5173
